# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/5sygy4bz205fn9hwwlvasi510c2k3l5b-cmake-3.22.3/bin/cmake

# The command to remove a file.
RM = /nix/store/5sygy4bz205fn9hwwlvasi510c2k3l5b-cmake-3.22.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tom.brossard/afs/SPE/Projects/OCR-Sudoku

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tom.brossard/afs/SPE/Projects/OCR-Sudoku

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/nix/store/5sygy4bz205fn9hwwlvasi510c2k3l5b-cmake-3.22.3/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/nix/store/5sygy4bz205fn9hwwlvasi510c2k3l5b-cmake-3.22.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tom.brossard/afs/SPE/Projects/OCR-Sudoku/CMakeFiles /home/tom.brossard/afs/SPE/Projects/OCR-Sudoku//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tom.brossard/afs/SPE/Projects/OCR-Sudoku/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/tom.brossard/afs/SPE/Projects/OCR-Sudoku/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OcrExe

# Build rule for target.
OcrExe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OcrExe
.PHONY : OcrExe

# fast build rule for target.
OcrExe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OcrExe.dir/build.make CMakeFiles/OcrExe.dir/build
.PHONY : OcrExe/fast

src/functions/test.o: src/functions/test.c.o
.PHONY : src/functions/test.o

# target to build an object file
src/functions/test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OcrExe.dir/build.make CMakeFiles/OcrExe.dir/src/functions/test.c.o
.PHONY : src/functions/test.c.o

src/functions/test.i: src/functions/test.c.i
.PHONY : src/functions/test.i

# target to preprocess a source file
src/functions/test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OcrExe.dir/build.make CMakeFiles/OcrExe.dir/src/functions/test.c.i
.PHONY : src/functions/test.c.i

src/functions/test.s: src/functions/test.c.s
.PHONY : src/functions/test.s

# target to generate assembly for a file
src/functions/test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OcrExe.dir/build.make CMakeFiles/OcrExe.dir/src/functions/test.c.s
.PHONY : src/functions/test.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OcrExe.dir/build.make CMakeFiles/OcrExe.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OcrExe.dir/build.make CMakeFiles/OcrExe.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OcrExe.dir/build.make CMakeFiles/OcrExe.dir/src/main.c.s
.PHONY : src/main.c.s

src/solver/read_file.o: src/solver/read_file.c.o
.PHONY : src/solver/read_file.o

# target to build an object file
src/solver/read_file.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OcrExe.dir/build.make CMakeFiles/OcrExe.dir/src/solver/read_file.c.o
.PHONY : src/solver/read_file.c.o

src/solver/read_file.i: src/solver/read_file.c.i
.PHONY : src/solver/read_file.i

# target to preprocess a source file
src/solver/read_file.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OcrExe.dir/build.make CMakeFiles/OcrExe.dir/src/solver/read_file.c.i
.PHONY : src/solver/read_file.c.i

src/solver/read_file.s: src/solver/read_file.c.s
.PHONY : src/solver/read_file.s

# target to generate assembly for a file
src/solver/read_file.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OcrExe.dir/build.make CMakeFiles/OcrExe.dir/src/solver/read_file.c.s
.PHONY : src/solver/read_file.c.s

src/solver/solver.o: src/solver/solver.c.o
.PHONY : src/solver/solver.o

# target to build an object file
src/solver/solver.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OcrExe.dir/build.make CMakeFiles/OcrExe.dir/src/solver/solver.c.o
.PHONY : src/solver/solver.c.o

src/solver/solver.i: src/solver/solver.c.i
.PHONY : src/solver/solver.i

# target to preprocess a source file
src/solver/solver.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OcrExe.dir/build.make CMakeFiles/OcrExe.dir/src/solver/solver.c.i
.PHONY : src/solver/solver.c.i

src/solver/solver.s: src/solver/solver.c.s
.PHONY : src/solver/solver.s

# target to generate assembly for a file
src/solver/solver.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OcrExe.dir/build.make CMakeFiles/OcrExe.dir/src/solver/solver.c.s
.PHONY : src/solver/solver.c.s

src/solver/sudoku.o: src/solver/sudoku.c.o
.PHONY : src/solver/sudoku.o

# target to build an object file
src/solver/sudoku.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OcrExe.dir/build.make CMakeFiles/OcrExe.dir/src/solver/sudoku.c.o
.PHONY : src/solver/sudoku.c.o

src/solver/sudoku.i: src/solver/sudoku.c.i
.PHONY : src/solver/sudoku.i

# target to preprocess a source file
src/solver/sudoku.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OcrExe.dir/build.make CMakeFiles/OcrExe.dir/src/solver/sudoku.c.i
.PHONY : src/solver/sudoku.c.i

src/solver/sudoku.s: src/solver/sudoku.c.s
.PHONY : src/solver/sudoku.s

# target to generate assembly for a file
src/solver/sudoku.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OcrExe.dir/build.make CMakeFiles/OcrExe.dir/src/solver/sudoku.c.s
.PHONY : src/solver/sudoku.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... OcrExe"
	@echo "... src/functions/test.o"
	@echo "... src/functions/test.i"
	@echo "... src/functions/test.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/solver/read_file.o"
	@echo "... src/solver/read_file.i"
	@echo "... src/solver/read_file.s"
	@echo "... src/solver/solver.o"
	@echo "... src/solver/solver.i"
	@echo "... src/solver/solver.s"
	@echo "... src/solver/sudoku.o"
	@echo "... src/solver/sudoku.i"
	@echo "... src/solver/sudoku.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/tom.brossard/afs/SPE/Projects/OCR-Sudoku/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

